apiVersion: apps/v1
kind: Deployment
metadata:
  name: host-name-deployment-ns
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app-pod-label
  template:
    metadata:
      name: spring-app-pod
      labels:
        app: spring-app-pod-label
    spec:
      containers:
        - name: spring-app
          image: ghcr.io/seungh0/k8s-spring-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: production
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 8080
  selector:
    app: spring-app-pod-label
  type: NodePort
