apiVersion: v1
kind: Pod
metadata:
  name: k8s-spring-deploy
spec:
  containers:
    - name: k8s-spring-deploy-container
      image: ghcr.io/seungh0/k8s-spring-test
      ports:
        - containerPort: 8080
          protocol: TCP