apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: spring-k8s
spec:
  ports:
    - name: web-port
      port: 80
      targetPort: 8080
      nodePort: 30000
  selector:
    app: spring-app-pod-label
  type: NodePort